### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by thomaskrause** [mfreiholz/humblelogging#20]
Thank you for this project. I would like to use it in one of my open source projects (Apache 2.0 licensed) but unfortunately I can't find any information on how Humble Logging is licensed. Is this an oversight from me or did you not decided on a license yet?

**Comment by mfreiholz** [comment]
Hi Thomas,
don't worry about the license. Feel free to use wherever you want.

Thanks for noticing this, i will add a LICENSE file tonight. It's probably going to be the Apache- or some kind of Beer-License :P
