### ISSUE TITLE
c++11 issue

### ISSUE THREAD

**Issue by MohammedZwayen** [mfreiholz/humblelogging#25]
dear sir
could you please help me out at building the library in the vs 2008
it seems that the library using c++11 where the vs2008 does not support it 
as you can see in the build output the main problems came from :
`Compiling...
spinlock_c11.cpp
..\src\util\spinlock_c11.cpp(3) : fatal error C1083: Cannot open include file: 'atomic': No such file or directory
mutex_c11.cpp
..\src\util\mutex_c11.cpp(2) : fatal error C1083: Cannot open include file: 'mutex': No such file or directory`

this is the complete outputs of build process:

`1>------ Rebuild All started: Project: ZERO_CHECK, Configuration: Debug Win32 ------
1>Deleting intermediate and output files for project 'ZERO_CHECK', configuration 'Debug|Win32'
1>Checking Build System
1>CMake is re-running because C:/Users/HP/Desktop/hot projects/humblelogging/build/CMakeFiles/generate.stamp is out-of-date.
1>  the file 'C:/Users/HP/Desktop/hot projects/humblelogging/CMakeLists.txt'
1>  is newer than 'C:/Users/HP/Desktop/hot projects/humblelogging/build/CMakeFiles/generate.stamp.depend'
1>  result='-1'
1>-- Configuring done
1>-- Generating done
1>-- Build files have been written to: C:/Users/HP/Desktop/hot projects/humblelogging/build
1>Build log was saved at "file://c:\Users\HP\Desktop\hot projects\humblelogging\build\ZERO_CHECK.dir\Debug\BuildLog.htm"
1>ZERO_CHECK - 0 error(s), 0 warning(s)
2>------ Rebuild All started: Project: humblelogging, Configuration: Debug Win32 ------
2>Deleting intermediate and output files for project 'humblelogging', configuration 'Debug|Win32'
2>Building Custom Rule C:/Users/HP/Desktop/hot projects/humblelogging/CMakeLists.txt
2>CMake is re-running because C:/Users/HP/Desktop/hot projects/humblelogging/build/CMakeFiles/generate.stamp is out-of-date.
2>  the file 'C:/Users/HP/Desktop/hot projects/humblelogging/CMakeLists.txt'
2>  is newer than 'C:/Users/HP/Desktop/hot projects/humblelogging/build/CMakeFiles/generate.stamp.depend'
2>  result='-1'
2>-- Configuring done
2>-- Generating done
2>-- Build files have been written to: C:/Users/HP/Desktop/hot projects/humblelogging/build
2>Compiling...
2>spinlock_c11.cpp
2>..\src\util\spinlock_c11.cpp(3) : fatal error C1083: Cannot open include file: 'atomic': No such file or directory
2>mutex_c11.cpp
2>..\src\util\mutex_c11.cpp(2) : fatal error C1083: Cannot open include file: 'mutex': No such file or directory
2>loglevel.cpp
2>logger.cpp
2>logevent.cpp
2>formatter.cpp
2>factory.cpp
2>configuration.cpp
2>appender.cpp
2>processinfo.cpp
2>patternconfigregistry.cpp
2>simpleconfiguration.cpp
2>defaultconfiguration.cpp
2>patternformatter.cpp
2>simpleformatter.cpp
2>rollingfileappender.cpp
2>nullappender.cpp
2>fileappender.cpp
2>consoleappender.cpp
2>Generating Code...
2>Build log was saved at "file://c:\Users\HP\Desktop\hot projects\humblelogging\build\humblelogging.dir\Debug\BuildLog.htm"
2>humblelogging - 2 error(s), 0 warning(s)
3>------ Rebuild All started: Project: basic_example, Configuration: Debug Win32 ------
3>Deleting intermediate and output files for project 'basic_example', configuration 'Debug|Win32'
3>Building Custom Rule C:/Users/HP/Desktop/hot projects/humblelogging/examples/basic/CMakeLists.txt
3>CMake is re-running because C:/Users/HP/Desktop/hot projects/humblelogging/build/examples/basic/CMakeFiles/generate.stamp is out-of-date.
3>  the file 'C:/Users/HP/Desktop/hot projects/humblelogging/examples/basic/CMakeLists.txt'
3>  is newer than 'C:/Users/HP/Desktop/hot projects/humblelogging/build/examples/basic/CMakeFiles/generate.stamp.depend'
3>  result='-1'
3>-- Configuring done
3>-- Generating done
3>-- Build files have been written to: C:/Users/HP/Desktop/hot projects/humblelogging/build
3>Compiling...
3>basic_example.cpp
3>Compiling manifest to resources...
3>Microsoft (R) Windows (R) Resource Compiler Version 6.0.5724.0
3>Copyright (C) Microsoft Corporation.  All rights reserved.
3>Linking...
3>LINK : fatal error LNK1104: cannot open file '..\..\Debug\humblelogging.lib'
3>Build log was saved at "file://c:\Users\HP\Desktop\hot projects\humblelogging\build\examples\basic\basic_example.dir\Debug\BuildLog.htm"
3>basic_example - 1 error(s), 0 warning(s)
========== Rebuild All: 1 succeeded, 2 failed, 0 skipped ==========
`
and after building process complete how should i generate .lib ?

**Comment by mfreiholz** [comment]
I close this, since the library no longer supports old compilers.
